### ISSUE TITLE
Zu viele Events

### ISSUE THREAD

**Issue by Laufesel** [Laufesel/Arcade-Machine#17]
Wenn man die Maus im Fenster dauernd bewegt werden so viele Events erfasst, dass die Keyboard Controls nicht mehr richtig funktionieren. Dann bewegt der Spieler sich komplett random

**Comment by PhilHolub** [comment]
kann man maus events nicht abstellen? Die brauchen wir ja eigentlich gar nicht

**Comment by Laufesel** [comment]
Müssen wir mal testen ob man Maus Events irgendwie rausfiltern kann

**Comment by Laufesel** [comment]
Das Problem ist, dass SDL_PollEvent nur ein Mal im Loop aufgerufen wird, das heißt es werden nur 50 Events pro Sekunde verarbeitet. (Gebunden an FPS)

**Comment by PhilHolub** [comment]
Sollen wir dann einfach mehrfach pollen?
